var goodsInfo = [{
	"newImg": "img/goodsList/while.png",
	"brandImg": "img/goodsList/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsList/gl06.jpg",
	"discount": "7.9折",
	"goodsNow": "￥689.0",
	"goodsOld": "￥870.0",
	"detail01": "爱马仕",
	"detail02": "蓝色橘彩星光淡",
	"detail03": "50毫升"
},
{
	"newImg": "img/goodsList/new.png",
	"brandImg": "img/goodsList/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsList/gl02.jpg",
	"discount": "8折",
	"goodsNow": "￥839.0",
	"goodsOld": "￥1045.0",
	"detail01": "迪奥",
	"detail02": "真我喷式",
	"detail03": "100毫升"
},
{
	"newImg": "img/goodsList/list.png",
	"brandImg": "img/goodsList/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsList/gl03.jpg",
	"discount": "6.7折",
	"goodsNow": "￥72.0",
	"goodsOld": "￥108.0",
	"detail01": "范思哲",
	"detail02": "香恋水晶淡",
	"detail03": "5毫升"
},
{
	"newImg": "img/goodsList/while.png",
	"brandImg": "img/goodsList/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsList/gl04.jpg",
	"discount": "3.4折",
	"goodsNow": "￥171.0",
	"goodsOld": "￥510.0",
	"detail01": " Calvin Klein",
	"detail02": "BE 卡莱比中性淡",
	"detail03": "100毫升"
},
{
	"newImg": "img/goodsList/while.png",
	"brandImg": "img/goodsList/jp_icon.png",
	"brandWord": "日本品牌",
	"goodsImg": "img/goodsList/gl05.jpg",
	"discount": "4.8折",
	"goodsNow": "￥199.0",
	"goodsOld": "￥415.0",
	"detail01": "安娜苏",
	"detail02": "许愿精灵  许愿精灵淡",
	"detail03": "30毫升"
},
{
	"newImg": "img/goodsList/while.png",
	"brandImg": "img/goodsList/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsList/gl01.jpg",
	"discount": "3.3折",
	"goodsNow": "￥288.0",
	"goodsOld": "￥870.0",
	"detail01": "BURBERRY",
	"detail02": "BRIT SHEER 红粉恋歌淡",
	"detail03": "100毫升"
},
{
	"newImg": "img/goodsList/new.png",
	"brandImg": "img/goodsList/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsList/gl07.jpg",
	"discount": "4.7折",
	"goodsNow": "￥410.0",
	"goodsOld": "￥870.0",
	"detail01": "GUCCI",
	"detail02": "罪爱燃情 罪爱夜 女性淡",
	"detail03": "50毫升"
},
{
	"newImg": "img/goodsList/new.png",
	"brandImg": "img/goodsList/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsList/gl08.jpg",
	"discount": "3.5折",
	"goodsNow": "￥240.0",
	"goodsOld": "￥680.0",
	"detail01": "宝格丽",
	"detail02": "OMNIA AMETHYSTE 紫晶纯香女士",
	"detail03": "40毫升"
},
{
	"newImg": "img/goodsList/while.png",
	"brandImg": "img/goodsList/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsList/gl09.jpg",
	"discount": "7.4折",
	"goodsNow": "￥48.2",
	"goodsOld": "￥65.0",
	"detail01": "露华浓",
	"detail02": "银色查理女士淡",
	"detail03": "100毫升"
},
{
	"newImg": "img/goodsList/while.png",
	"brandImg": "img/goodsList/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsList/gl10.jpg",
	"discount": "8.8折",
	"goodsNow": "￥752.0",
	"goodsOld": "￥850.0",
	"detail01": "香奈儿",
	"detail02": "邂逅喷式淡",
	"detail03": "50毫升"
},
{
	"newImg": "img/goodsList/while.png",
	"brandImg": "img/goodsList/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsList/gl11.jpg",
	"discount": "9.7折",
	"goodsNow": "￥949.0",
	"goodsOld": "￥980.0",
	"detail01": "香奈儿",
	"detail02": "可可小姐喷式",
	"detail03": "50毫升"
},
{
	"newImg": "img/goodsList/list.png",
	"brandImg": "img/goodsList/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsList/gl12.jpg",
	"discount": "4.3折",
	"goodsNow": "￥359.0",
	"goodsOld": "￥830.0",
	"detail01": "宝格丽",
	"detail02": "OMNIA CRYSTRALLINE 晶莹纯香女士淡",
	"detail03": "65毫升"
},
{
	"newImg": "img/goodsList/while.png",
	"brandImg": "img/goodsList/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsList/gl13.jpg",
	"discount": "8.6折",
	"goodsNow": "￥915.0",
	"goodsOld": "￥1060.0",
	"detail01": "香奈儿",
	"detail02": "五号喷式",
	"detail03": "50毫升"
},
{
	"newImg": "img/goodsList/new.png",
	"brandImg": "img/goodsList/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsList/gl14.jpg",
	"discount": "8.1折",
	"goodsNow": "￥999.0",
	"goodsOld": "￥1240.0",
	"detail01": "香奈儿",
	"detail02": "粉红邂逅喷式淡",
	"detail03": "100毫升"
},
{
	"newImg": "img/goodsList/while.png",
	"brandImg": "img/goodsList/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsList/gl15.jpg",
	"discount": "9折",
	"goodsNow": "￥44.0",
	"goodsOld": "￥49.0",
	"detail01": "菲拉格慕",
	"detail02": "INCANTO SHINE 闪耀光采迷你淡",
	"detail03": "5毫升"
},
{
	"newImg": "img/goodsList/while.png",
	"brandImg": "img/goodsList/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsList/gl16.jpg",
	"discount": "6.3折",
	"goodsNow": "￥399.0",
	"goodsOld": "￥630.0",
	"detail01": "Marc Jacobs",
	"detail02": "雏菊之梦女性淡",
	"detail03": "50毫升"
},
{
	"newImg": "img/goodsList/while.png",
	"brandImg": "img/goodsList/jp_icon.png",
	"brandWord": "日本品牌",
	"goodsImg": "img/goodsList/gl17.jpg",
	"discount": "5.7折",
	"goodsNow": "￥56.0",
	"goodsOld": "￥99.0",
	"detail01": "安娜苏",
	"detail02": "许愿精灵 许愿精灵迷你淡",
	"detail03": "4毫升"
},
{
	"newImg": "img/goodsList/new.png",
	"brandImg": "img/goodsList/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsList/gl18.jpg",
	"discount": "4.9折",
	"goodsNow": "￥359.0",
	"goodsOld": "￥730.0",
	"detail01": "Marc Jacobs",
	"detail02": "DAISY 清甜雏菊女性淡",
	"detail03": "75毫升"
},
{
	"newImg": "img/goodsList/while.png",
	"brandImg": "img/goodsList/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsList/gl19.jpg",
	"discount": "9.1折",
	"goodsNow": "￥619.0",
	"goodsOld": "￥679.0",
	"detail01": "菲拉格慕",
	"detail02": "蔚蓝之水淡",
	"detail03": "100毫升"
},
{
	"newImg": "img/goodsList/list.png",
	"brandImg": "img/goodsList/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsList/gl20.jpg",
	"discount": "3.5折",
	"goodsNow": "￥209.0",
	"goodsOld": "￥600.0",
	"detail01": "Calvin Klein",
	"detail02": "ONE 卡莱优淡",
	"detail03": "200毫升"
},
{
	"newImg": "img/goodsList/while.png",
	"brandImg": "img/goodsList/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsList/gl21.jpg",
	"discount": "5.5折",
	"goodsNow": "￥575.0",
	"goodsOld": "￥1045.0",
	"detail01": "爱马仕",
	"detail02": "尼羅河花園 淡",
	"detail03": "100毫升"
},
{
	"newImg": "img/goodsList/while.png",
	"brandImg": "img/goodsList/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsList/gl22.jpg",
	"discount": "5.6折",
	"goodsNow": "￥424.0",
	"goodsOld": "￥755.0",
	"detail01": "爱马仕",
	"detail02": "李先生的花园 淡",
	"detail03": "50毫升"
},
{
	"newImg": "img/goodsList/while.png",
	"brandImg": "img/goodsList/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsList/gl23.jpg",
	"discount": "8.7折",
	"goodsNow": "￥782.0",
	"goodsOld": "￥895.0",
	"detail01": "菲拉格慕",
	"detail02": "永远的芭蕾情结女士",
	"detail03": "100毫升"
},
{
	"newImg": "img/goodsList/new.png",
	"brandImg": "img/goodsList/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsList/gl24.jpg",
	"discount": "9.1折",
	"goodsNow": "￥635.0",
	"goodsOld": "￥698.0",
	"detail01": "蓝色情人",
	"detail02": "Rosa Eau de Parfume 女士淡",
	"detail03": "100毫升"
}]
