var active01 = [{
	"brandImg": "img/goodsActive/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsActive/ga01.jpg",
	"discount": "7.9折",
	"goodsNow": "￥45.3",
	"goodsOld": "￥60.0",
	"detail01": "I-Mju HATOMUGI",
	"detail02": "日本薏仁化妆水G 附送化妆水喷雾套装",
	"detail03": "2件套",
	"goodsTag": "直降"
},
{
	"brandImg": " ",
	"brandWord": " ",
	"goodsImg": "img/goodsActive/ga02.jpg",
	"discount": "8.1折",
	"goodsNow": "￥250.0",
	"goodsOld": "￥308.0",
	"detail01": "A.H.C",
	"detail02": "高效水合透明质酸旅补湿水",
	"detail03": "1000毫升",
	"goodsTag": "直降"
},
{
	"brandImg": " ",
	"brandWord": " ",
	"goodsImg": "img/goodsActive/ga03.jpg",
	"discount": "5.3折",
	"goodsNow": "￥38.0",
	"goodsOld": "￥72.0",
	"detail01": "ATREUS",
	"detail02": "Atreus VC亮白保湿水",
	"detail03": "500毫升",
	"goodsTag": "已售4件"
},
{
	"brandImg": " ",
	"brandWord": " ",
	"goodsImg": "img/goodsActive/ga04.jpg",
	"discount": "6.1折",
	"goodsNow": "￥165.0",
	"goodsOld": "￥272.0",
	"detail01": "HABA",
	"detail02": "优白系列   HABA 润泽柔肤水 G露",
	"detail03": "180毫升",
	"goodsTag": "已售8件"
},
{
	"brandImg": "img/goodsActive/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsActive/ga05.jpg",
	"discount": "8.7折",
	"goodsNow": "￥199.0",
	"goodsOld": "￥230.0",
	"detail01": "科颜氏",
	"detail02": "男士全效爽肤水",
	"detail03": "250毫升",
	"goodsTag": "直降"
},
{
	"brandImg": " ",
	"brandWord": " ",
	"goodsImg": "img/goodsActive/ga06.jpg",
	"discount": "8.2折",
	"goodsNow": "￥106.0",
	"goodsOld": "￥130.0",
	"detail01": "A.H.C",
	"detail02": "高效B5水合爽肤水",
	"detail03": "120毫升",
	"goodsTag": "直降"
},
{
	"brandImg": "img/goodsActive/jp_icon.png",
	"brandWord": "日本品牌",
	"goodsImg": "img/goodsActive/ga07.jpg",
	"discount": "6.3折",
	"goodsNow": "￥38.0",
	"goodsOld": "￥60.0",
	"detail01": "资生堂",
	"detail02": "豪华级嘉美艳容露",
	"detail03": "150毫升",
	"goodsTag": "直降"
},
{
	"brandImg": "img/goodsActive/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsActive/ga08.jpg",
	"discount": "7折",
	"goodsNow": "￥308.0",
	"goodsOld": "￥440.0",
	"detail01": "雅诗兰黛",
	"detail02": "红石榴系列   鲜亮焕采能量水(滋润型)",
	"detail03": "200毫升",
	"goodsTag": "已售4件"
},
{
	"brandImg": "img/goodsActive/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsActive/ga09.jpg",
	"discount": "1折",
	"goodsNow": "￥182.3",
	"goodsOld": "￥1789.0",
	"detail01": "MVSK",
	"detail02": "24K金羊胎素肌底再生活膚露(微乳化技術)",
	"detail03": "110毫升",
	"goodsTag": "直降"
},
{
	"brandImg": "img/goodsActive/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsActive/ga10.jpg",
	"discount": "8.6折",
	"goodsNow": "￥109.0",
	"goodsOld": "￥127.0",
	"detail01": "欧缇丽",
	"detail02": "葡萄籽保湿喷雾",
	"detail03": "200毫升",
	"goodsTag": "直降"
},
{
	"brandImg": "img/goodsActive/korean_icon.png",
	"brandWord": "韩国品牌",
	"goodsImg": "img/goodsActive/ga11.jpg",
	"discount": "3.3折",
	"goodsNow": "￥126.0",
	"goodsOld": "￥380.0",
	"detail01": "伊思",
	"detail02": "化妆水   晶钻美肤蜗牛爽肤水 (清爽型)",
	"detail03": "140毫升",
	"goodsTag": "直降"
},
{
	"brandImg": "img/goodsActive/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsActive/ga12.jpg",
	"discount": "7.8折",
	"goodsNow": "￥163.0",
	"goodsOld": "￥210.0",
	"detail01": "科颜氏",
	"detail02": "高保湿清爽柔肤水",
	"detail03": "250毫升",
	"goodsTag": "直降"
},
{
	"brandImg": "img/goodsActive/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsActive/ga13.jpg",
	"discount": "1折",
	"goodsNow": "￥145.8",
	"goodsOld": "￥1431.0",
	"detail01": "MVSK",
	"detail02": "龙血树活氧细胞肌底升华露",
	"detail03": "120毫升",
	"goodsTag": "直降"
},
{
	"brandImg": "img/goodsActive/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsActive/ga14.jpg",
	"discount": "6折",
	"goodsNow": "￥52.0",
	"goodsOld": "￥86.0",
	"detail01": "依云",
	"detail02": "矿泉保湿喷雾",
	"detail03": "300毫升",
	"goodsTag": "直降"
},
{
	"brandImg": "img/goodsActive/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsActive/ga15.jpg",
	"discount": "5.4折",
	"goodsNow": "￥99.0",
	"goodsOld": "￥185.0",
	"detail01": "雅漾",
	"detail02": "舒护活泉喷雾",
	"detail03": "300毫升",
	"goodsTag": "直降"
},
{
	"brandImg": "img/goodsActive/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsActive/ga16.jpg",
	"discount": "6.9折",
	"goodsNow": "￥288.0",
	"goodsOld": "￥420.0",
	"detail01": "兰蔻",
	"detail02": "清滢嫩肤水(蓝水)",
	"detail03": "400毫升",
	"goodsTag": "已售1件"
}]

var active02 = [{
	"brandImg": "img/goodsActive/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsActive/ry01.jpg",
	"discount": "7.5折",
	"goodsNow": "￥187.0",
	"goodsOld": "￥251.0",
	"detail01": "疯狂嬉皮",
	"detail02": "活萃维A抗老精华",
	"detail03": "30毫升",
	"goodsTag": "直降"
},
{
	"brandImg": " ",
	"brandWord": " ",
	"goodsImg": "img/goodsActive/ry02.jpg",
	"discount": "7.7折",
	"goodsNow": "￥89.0",
	"goodsOld": "￥115.0",
	"detail01": "THE ORDINARY",
	"detail02": "NIACINAMIDE 10% + ZINC 1%精华",
	"detail03": "30毫升",
	"goodsTag": "已售3件"
},
{
	"brandImg": "img/goodsActive/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsActive/ry03.jpg",
	"discount": "6.2折",
	"goodsNow": "￥92.0",
	"goodsOld": "￥148.0",
	"detail01": "XHEKPON",
	"detail02": "胶原蛋白颈纹霜",
	"detail03": "40毫升",
	"goodsTag": "已售6件"
},
{
	"brandImg": "img/goodsActive/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsActive/ry04.jpg",
	"discount": "1折",
	"goodsNow": "￥299.0",
	"goodsOld": "￥3115.0",
	"detail01": "DEVDO",
	"detail02": "类胎盘素双干细胞深层焕白淡班导入精华",
	"detail03": "30件",
	"goodsTag": "直降"
},
{
	"brandImg": "img/goodsActive/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsActive/ry05.jpg",
	"discount": "7.3折",
	"goodsNow": "￥72.0",
	"goodsOld": "￥99.0",
	"detail01": "芭乐雅",
	"detail02": "玻尿酸补湿紧致精华安瓶",
	"detail03": "7件",
	"goodsTag": "已售3件"
},
{
	"brandImg": "img/goodsActive/jp_icon.png",
	"brandWord": "日本品牌",
	"goodsImg": "img/goodsActive/ry06.jpg",
	"discount": "1折",
	"goodsNow": "￥214.0",
	"goodsOld": "￥2095.0",
	"detail01": "COYU",
	"detail02": "10000ppm涂抹式蓝铜水光针导入精华(蓝光针)",
	"detail03": "12件",
	"goodsTag": "已售10件"
},
{
	"brandImg": "img/goodsActive/korean_icon.png",
	"brandWord": "韩国品牌",
	"goodsImg": "img/goodsActive/ry07.jpg",
	"discount": "3.9折",
	"goodsNow": "￥168.0",
	"goodsOld": "￥435.0",
	"detail01": "Dr. Jart+",
	"detail02": "V7多元维他命再生透白系列   V7维生素焕颜亮白霜",
	"detail03": "50毫升 ",
	"goodsTag": "已售5件"
},
{
	"brandImg": " ",
	"brandWord": " ",
	"goodsImg": "img/goodsActive/ry08.jpg",
	"discount": "5.7折",
	"goodsNow": "￥169.0",
	"goodsOld": "￥298.0",
	"detail01": "HABA",
	"detail02": "鲨烷精纯美容油",
	"detail03": "30毫升 ",
	"goodsTag": "已售14件"
},
{
	"brandImg": "img/goodsActive/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsActive/ry09.jpg",
	"discount": "5.1折",
	"goodsNow": "￥81.0",
	"goodsOld": "￥160.0",
	"detail01": "兰蔻",
	"detail02": "兰蔻水份缘舒缓凝霜",
	"detail03": "15毫升",
	"goodsTag": "直降"
},
{
	"brandImg": "img/goodsActive/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsActive/ry10.jpg",
	"discount": "6.7折",
	"goodsNow": "￥429.0",
	"goodsOld": "￥640.0",
	"detail01": "雅诗兰黛",
	"detail02": "红石榴系列   鲜活亮采晚霜",
	"detail03": "50毫升",
	"goodsTag": "直降"
},
{
	"brandImg": "img/goodsActive/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsActive/ry11.jpg",
	"discount": "6.4折",
	"goodsNow": "￥203.0",
	"goodsOld": "￥315.0",
	"detail01": "倩碧",
	"detail02": "护肤三部曲   卓越润肤乳(天才黄油+)",
	"detail03": "125毫升",
	"goodsTag": "已售15件"
},
{
	"brandImg": "img/goodsActive/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsActive/ry12.jpg",
	"discount": "2.9折",
	"goodsNow": "￥90.0",
	"goodsOld": "￥308.0",
	"detail01": "Vitacreme B12",
	"detail02": "维他命B12面霜",
	"detail03": "50毫升 ",
	"goodsTag": "已售4件"
},
{
	"brandImg": "img/goodsActive/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsActive/ry13.jpg",
	"discount": "7.3折",
	"goodsNow": "￥257.0",
	"goodsOld": "￥350.0",
	"detail01": "科颜氏",
	"detail02": "高保湿系列   高保湿霜",
	"detail03": "50毫升 ",
	"goodsTag": "直降"
},
{
	"brandImg": "img/goodsActive/jp_icon.png",
	"brandWord": "日本品牌",
	"goodsImg": "img/goodsActive/ry14.jpg",
	"discount": "7.2折",
	"goodsNow": "￥149.0",
	"goodsOld": "￥208.0",
	"detail01": "珂润",
	"detail02": "润浸保湿滋养乳霜",
	"detail03": "40克 ",
	"goodsTag": "已售6件"
},
{
	"brandImg": "img/goodsActive/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsActive/ry15.jpg",
	"discount": "3.3折",
	"goodsNow": "￥72.5",
	"goodsOld": "￥220.0",
	"detail01": "巴黎欧莱雅",
	"detail02": "光学嫩肤系列   活力紧致光学嫩肤活肌修护高效精华水",
	"detail03": "175毫升 ",
	"goodsTag": "直降"
},
{
	"brandImg": "img/goodsActive/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsActive/ry16.jpg",
	"discount": "7.3折",
	"goodsNow": "￥429.0",
	"goodsOld": "￥590.0",
	"detail01": "雅诗兰黛",
	"detail02": "红石榴系列   鲜活亮采面霜",
	"detail03": "50毫升 ",
	"goodsTag": "已售7件"
},
{
	"brandImg": "img/goodsActive/jp_icon.png",
	"brandWord": "日本品牌",
	"goodsImg": "img/goodsActive/ry17.jpg",
	"discount": "5.2折",
	"goodsNow": "￥45.4",
	"goodsOld": "￥88.0",
	"detail01": "I-Mju HATOMUGI",
	"detail02": "日本薏仁保湿水凝霜",
	"detail03": "180克 ",
	"goodsTag": "直降"
},
{
	"brandImg": "img/goodsActive/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsActive/ry18.jpg",
	"discount": "6折",
	"goodsNow": "￥979.0",
	"goodsOld": "￥1640.0",
	"detail01": "娇兰",
	"detail02": "蜂皇修复精华",
	"detail03": "50毫升 ",
	"goodsTag": "已售2件"
},
{
	"brandImg": "img/goodsActive/jp_icon.png",
	"brandWord": "日本品牌",
	"goodsImg": "img/goodsActive/ry19.jpg",
	"discount": "7.5折",
	"goodsNow": "￥359.0",
	"goodsOld": "￥480.0",
	"detail01": "资生堂",
	"detail02": "盼丽风姿系列   24小时抗皱日霜SPF15",
	"detail03": "50毫升 ",
	"goodsTag": "直降"
},
{
	"brandImg": "img/goodsActive/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsActive/ry20.jpg",
	"discount": "9折",
	"goodsNow": "￥539.0",
	"goodsOld": "￥600.0",
	"detail01": "雅诗兰黛",
	"detail02": "MICRO ESSENCE   肌初赋活原生液",
	"detail03": "150毫升 ",
	"goodsTag": "已售2件"
},
{
	"brandImg": "img/goodsActive/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsActive/ry21.jpg",
	"discount": "9.2折",
	"goodsNow": "￥449.0",
	"goodsOld": "￥490.0",
	"detail01": "fresh",
	"detail02": "玫瑰润泽保湿系列   玫瑰润泽密集保湿精华露",
	"detail03": "30毫升 ",
	"goodsTag": "直降"
},
{
	"brandImg": "img/goodsActive/korean_icon.png",
	"brandWord": "韩国品牌",
	"goodsImg": "img/goodsActive/ry22.jpg",
	"discount": "7.1折",
	"goodsNow": "￥621.0",
	"goodsOld": "￥870.0",
	"detail01": "雪花秀",
	"detail02": "优白系列   润致焕活肌底精华露",
	"detail03": "90毫升 ",
	"goodsTag": "直降"
},
{
	"brandImg": "img/goodsActive/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsActive/ry23.jpg",
	"discount": "5.5折",
	"goodsNow": "￥252.0",
	"goodsOld": "￥455.0",
	"detail01": "欧碧泉",
	"detail02": "活泉润透系列   活泉润透水分露(绿活泉)",
	"detail03": "50毫升 ",
	"goodsTag": "直降"
},
{
	"brandImg": "img/goodsActive/jp_icon.png",
	"brandWord": "日本品牌",
	"goodsImg": "img/goodsActive/ry24.jpg",
	"discount": "7.5折",
	"goodsNow": "￥359.0",
	"goodsOld": "￥480.0",
	"detail01": "资生堂",
	"detail02": "盼丽风姿系列   抗皱日乳SPF15",
	"detail03": "75毫升 ",
	"goodsTag": "已售2件"
},
{
	"brandImg": "img/goodsActive/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsActive/ry25.jpg",
	"discount": "5.7折",
	"goodsNow": "￥89.0",
	"goodsOld": "￥155.0",
	"detail01": "兰蔻",
	"detail02": "小黑瓶精华肌底液 升级版 小样",
	"detail03": "7毫升 ",
	"goodsTag": "已售12件"
},
{
	"brandImg": "img/goodsActive/korean_icon.png",
	"brandWord": "韩国品牌",
	"goodsImg": "img/goodsActive/ry26.jpg",
	"discount": "5.5折",
	"goodsNow": "￥83.0",
	"goodsOld": "￥150.0",
	"detail01": "GUERISSON",
	"detail02": "奇迹马油霜",
	"detail03": "70克 ",
	"goodsTag": "直降"
}]

var active03 = [{
	"brandImg": " ",
	"brandWord": " ",
	"goodsImg": "img/goodsActive/mm01.jpg",
	"discount": "3.7折",
	"goodsNow": "￥37.0",
	"goodsOld": "￥99.0",
	"detail01": "安娜贝拉",
	"detail02": "海藻补水滋养面膜",
	"detail03": " "
},
{
	"brandImg": "img/goodsActive/korean_icon.png",
	"brandWord": "韩国品牌",
	"goodsImg": "img/goodsActive/mm02.jpg",
	"discount": "3.8折",
	"goodsNow": "￥59.0",
	"goodsOld": "￥156.0",
	"detail01": "JMsolution",
	"detail02": "肌司研蜜萤润蜂胶面膜",
	"detail03": "30毫升X10"
},
{
	"brandImg": " ",
	"brandWord": " ",
	"goodsImg": "img/goodsActive/mm03.jpg",
	"discount": "6.6折",
	"goodsNow": "￥62.0",
	"goodsOld": "￥94.0",
	"detail01": "泰国妆蕾",
	"detail02": "泰国妆蕾蚕丝面膜(金)",
	"detail03": "10片/盒 "
},
{
	"brandImg": "img/goodsActive/korean_icon.png",
	"brandWord": "韩国品牌",
	"goodsImg": "img/goodsActive/mm04.jpg",
	"discount": "5.7折",
	"goodsNow": "￥85.0",
	"goodsOld": "￥150.0",
	"detail01": "SNP",
	"detail02": "京剧面膜系列   京剧水库保湿面膜",
	"detail03": "10片"
},
{
	"brandImg": "img/goodsActive/korean_icon.png",
	"brandWord": "韩国品牌",
	"goodsImg": "img/goodsActive/mm05.jpg",
	"discount": "2.8折",
	"goodsNow": "￥48.0",
	"goodsOld": "￥170.0",
	"detail01": "SNP",
	"detail02": "精华面膜系列   金丝燕窝深层保湿面膜",
	"detail03": "10片"
},
{
	"brandImg": "img/goodsActive/korean_icon.png",
	"brandWord": "韩国品牌",
	"goodsImg": "img/goodsActive/mm06.jpg",
	"discount": "3.5折",
	"goodsNow": "￥59.0",
	"goodsOld": "￥170.0",
	"detail01": "SNP",
	"detail02": "精华面膜系列   水钻美白保湿面膜",
	"detail03": "10片"
},
{
	"brandImg": "img/goodsActive/korean_icon.png",
	"brandWord": "韩国品牌",
	"goodsImg": "img/goodsActive/mm07.jpg",
	"discount": "4折",
	"goodsNow": "￥79.0",
	"goodsOld": "￥199.0",
	"detail01": "JMsolution",
	"detail02": "肌司研蚕丝安基酸水基美白面膜",
	"detail03": "45克X10"
},
{
	"brandImg": " ",
	"brandWord": " ",
	"goodsImg": "img/goodsActive/mm08.jpg",
	"discount": "5.3折",
	"goodsNow": "￥52.0",
	"goodsOld": "￥98.0",
	"detail01": "泰国妆蕾",
	"detail02": "泰国妆蕾蚕丝面膜(銀)",
	"detail03": "10片/盒 "
},
{
	"brandImg": "img/goodsActive/korean_icon.png",
	"brandWord": "韩国品牌",
	"goodsImg": "img/goodsActive/mm09.jpg",
	"discount": "5.4折",
	"goodsNow": "￥279.0",
	"goodsOld": "￥519.0",
	"detail01": "雪花秀",
	"detail02": "与润修护睡眠面膜",
	"detail03": "120毫升"
},
{
	"brandImg": "img/goodsActive/korean_icon.png",
	"brandWord": "韩国品牌",
	"goodsImg": "img/goodsActive/mm10.jpg",
	"discount": "3.5折",
	"goodsNow": "￥52.0",
	"goodsOld": "￥147.0",
	"detail01": "丽得姿",
	"detail02": "氨基酸针剂水库面膜",
	"detail03": "10片"
},
{
	"brandImg": "img/goodsActive/korean_icon.png",
	"brandWord": "韩国品牌",
	"goodsImg": "img/goodsActive/mm11.jpg",
	"discount": "3.9折",
	"goodsNow": "￥78.0",
	"goodsOld": "￥200.0",
	"detail01": "美迪惠尔",
	"detail02": "高效特强保湿导入面膜",
	"detail03": "25 毫升 x 10"
},
{
	"brandImg": "img/goodsActive/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsActive/mm12.jpg",
	"discount": "4.4折",
	"goodsNow": "￥183.0",
	"goodsOld": "￥420.0",
	"detail01": "彼得罗夫",
	"detail02": "青瓜保湿系列   青瓜面膜",
	"detail03": "150毫升 "
},
{
	"brandImg": "img/goodsActive/korean_icon.png",
	"brandWord": "韩国品牌",
	"goodsImg": "img/goodsActive/mm13.jpg",
	"discount": "3.4折",
	"goodsNow": "￥69.0",
	"goodsOld": "￥202.0",
	"detail01": "VT",
	"detail02": "积雪草皮肤修复面膜",
	"detail03": "25克x10片"
},
{
	"brandImg": "img/goodsActive/korean_icon.png",
	"brandWord": "韩国品牌",
	"goodsImg": "img/goodsActive/mm14.jpg",
	"discount": "6.4折",
	"goodsNow": "￥95.0",
	"goodsOld": "￥149.0",
	"detail01": "PAPA RECIPE",
	"detail02": "面膜系列   春雨蜂蜜面膜",
	"detail03": "10片"
},
{
	"brandImg": "img/goodsActive/korean_icon.png",
	"brandWord": "韩国品牌",
	"goodsImg": "img/goodsActive/mm15.jpg",
	"discount": "5.3折",
	"goodsNow": "￥89.0",
	"goodsOld": "￥168.0",
	"detail01": "JayJun",
	"detail02": "补水保湿三部曲水光面膜",
	"detail03": "10片"
},
{
	"brandImg": "img/goodsActive/korean_icon.png",
	"brandWord": "韩国品牌",
	"goodsImg": "img/goodsActive/mm16.jpg",
	"discount": "3.5折",
	"goodsNow": "￥59.0",
	"goodsOld": "￥170.0",
	"detail01": "SNP",
	"detail02": "精华面膜系列   竹炭黑炭面膜",
	"detail03": "10片"
},

{
	"brandImg": "img/goodsActive/korean_icon.png",
	"brandWord": "韩国品牌",
	"goodsImg": "img/goodsActive/mm17.jpg",
	"discount": "3.2折",
	"goodsNow": "￥55.0",
	"goodsOld": "￥170.0",
	"detail01": "SNP",
	"detail02": "金装猪皮骨胶原面膜",
	"detail03": "10片"
},
{
	"brandImg": "img/goodsActive/korean_icon.png",
	"brandWord": "韩国品牌",
	"goodsImg": "img/goodsActive/mm18.jpg",
	"discount": "2.7折",
	"goodsNow": "￥40.0",
	"goodsOld": "￥150.0",
	"detail01": "SNP",
	"detail02": "动物面膜系列   老虎抗皱紧致面膜",
	"detail03": "10片"
},
{
	"brandImg": "img/goodsActive/tw_icon.png",
	"brandWord": "台湾品牌",
	"goodsImg": "img/goodsActive/mm19.jpg",
	"discount": "5.1折",
	"goodsNow": "￥40.0",
	"goodsOld": "￥79.0",
	"detail01": "森田药妆",
	"detail02": "保湿锁水系列   玻尿酸复合原液面膜",
	"detail03": "5片"
},
{
	"brandImg": "img/goodsActive/jp_icon.png",
	"brandWord": "日本品牌",
	"goodsImg": "img/goodsActive/mm20.jpg",
	"discount": "8折",
	"goodsNow": "￥1004.0",
	"goodsOld": "￥1260.0",
	"detail01": "SK-II",
	"detail02": "护肤面膜(青春敷面膜)",
	"detail03": "10片"
},
{
	"brandImg": "img/goodsActive/korean_icon.png",
	"brandWord": "韩国品牌",
	"goodsImg": "img/goodsActive/ry21.jpg",
	"discount": "2.9折",
	"goodsNow": "￥54.0",
	"goodsOld": "￥185.0",
	"detail01": "WONJIN EFFECT",
	"detail02": "焕能再生吊瓶面膜",
	"detail03": "30克x10入 "
},
{
	"brandImg": "img/goodsActive/korean_icon.png",
	"brandWord": "韩国品牌",
	"goodsImg": "img/goodsActive/ry22.jpg",
	"discount": "3.2折",
	"goodsNow": "￥63.0",
	"goodsOld": "￥199.0",
	"detail01": "JMsolution",
	"detail02": "水滋养丝滑蚕丝面膜（黑臻版）",
	"detail03": "35毫升X10 "
},
{
	"brandImg": "img/goodsActive/korean_icon.png",
	"brandWord": "韩国品牌",
	"goodsImg": "img/goodsActive/ry23.jpg",
	"discount": "2.8折",
	"goodsNow": "￥51.0",
	"goodsOld": "￥182.0",
	"detail01": "WONJIN EFFECT",
	"detail02": "透明质酸安瓶补水面膜",
	"detail03": "30克x10入 "
},
{
	"brandImg": "img/goodsActive/korean_icon.png",
	"brandWord": "韩国品牌",
	"goodsImg": "img/goodsActive/ry24.jpg",
	"discount": "3折",
	"goodsNow": "￥125.0",
	"goodsOld": "￥410.0",
	"detail01": "香蒲丽",
	"detail02": "黄金精华面膜",
	"detail03": "50克+4.5克 x 5 "
},
{
	"brandImg": "img/goodsActive/korean_icon.png",
	"brandWord": "韩国品牌",
	"goodsImg": "img/goodsActive/mm25.jpg",
	"discount": "4.4折",
	"goodsNow": "￥65.0",
	"goodsOld": "￥147.0",
	"detail01": "JMsolution",
	"detail02": "青光海洋珍珠面膜三部曲",
	"detail03": "10片"
},
{
	"brandImg": "img/goodsActive/korean_icon.png",
	"brandWord": "韩国品牌",
	"goodsImg": "img/goodsActive/mm26.jpg",
	"discount": "4.4折",
	"goodsNow": "￥269.0",
	"goodsOld": "￥610.0",
	"detail01": "后",
	"detail02": "鹿茸面膜",
	"detail03": "120毫升"
},
{
	"brandImg": "img/goodsActive/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsActive/mm27.jpg",
	"discount": "1折",
	"goodsNow": "￥145.8",
	"goodsOld": "￥1431.0",
	"detail01": "MVSK",
	"detail02": "24K金羊胎素再生面膜(三段式程序)",
	"detail03": "100 毫升 "
},
{
	"brandImg": "img/goodsActive/korean_icon.png",
	"brandWord": "韩国品牌",
	"goodsImg": "img/goodsActive/mm28.jpg",
	"discount": "5.8折",
	"goodsNow": "￥87.0",
	"goodsOld": "￥149.0",
	"detail01": "PAPA RECIPE",
	"detail02": "春雨蜜罐美白面膜 (10 片装)",
	"detail03": "10片"
},
{
	"brandImg": "img/goodsActive/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsActive/mm29.jpg",
	"discount": "6.7折",
	"goodsNow": "￥669.0",
	"goodsOld": "￥995.0",
	"detail01": "瑞士葆丽美",
	"detail02": "水份弹性面膜",
	"detail03": "200 毫升 "
},
{
	"brandImg": "img/goodsActive/jp_icon.png",
	"brandWord": "日本品牌",
	"goodsImg": "img/goodsActive/mm30.jpg",
	"discount": "3.5折",
	"goodsNow": "￥35.0",
	"goodsOld": "￥99.0",
	"detail01": "Barrier Repair (Mandom Corp)",
	"detail02": "曼丹婴儿肌 保湿润肌面膜",
	"detail03": "10片"
},
{
	"brandImg": "img/goodsActive/western_icon.png",
	"brandWord": "欧美品牌",
	"goodsImg": "img/goodsActive/mm31.jpg",
	"discount": "4.2折",
	"goodsNow": "￥118.0",
	"goodsOld": "￥280.0",
	"detail01": "贝佳斯",
	"detail02": "Signature系列   矿物营养泥浆面膜(绿泥)",
	"detail03": "212克"
},
{
	"brandImg": "img/goodsActive/jp_icon.png",
	"brandWord": "日本品牌",
	"goodsImg": "img/goodsActive/mm32.jpg",
	"discount": "8.8折",
	"goodsNow": "￥649.0",
	"goodsOld": "￥740.0",
	"detail01": "SK-II",
	"detail02": "Pitera™ 精华系列   护肤面膜",
	"detail03": "6片"
}]